### ISSUE TITLE
Import of open changes in old git

### ISSUE THREAD

**Issue by kusterjs** [vatsimnetwork/vatspy-data-project#11]
Please integrate the open changes from the previous used git (FlynZSky/VAT-Spy-Client-Data-Update-Project).

**Comment by FlynZSky** [comment]
In progress.

**Comment by prryplatypus** [comment]
Since each division can now submit their updates directly to this repo and VATSPY will automatically use it, I'm now closing this issue in order to keep this repo as the single "source of truth". There's been plenty of changes made here since this repo was created, and it would be harder at this point trying to merge old & new files together than having each division submit the necessary changes directly.
