### ISSUE TITLE
Add more documentation for columns of FIRs and how they map to FIR boundaries and callsigns

### ISSUE THREAD

**Issue by marvk** [vatsimnetwork/vatspy-data-project#197]
Currently, there are several issues with FIR boundaries.

1. What is the `extension` column on FIRs in `FIRBoundaries.dat`? Sometimes, this seems to denote a FIR that is split along the antimeridian (`UHMM`, `PAZA`, `UHPP`, `KZAK`, `NFFF`, `NZZO`), in other cases it seems to denote an undocumented extension of an oceanic (`CZQX Oceanic`, `EGGX Oceanic`) or a non-oceanic FIR (`CZQX`, `ESOS`).

   Vatspy itself seems to merge the extensions crossing the antimeridian, but seems to ignore extensions otherwise. What is the reason for those FIRs having extensions, are they used, but only sometimes, and how would VATSpy know?

2. What do the columns `PREFIX POSITION` and the fourth, unnamed column for FIRs in `VATSpy.dat` denote? I figure it has to do something with the controllers callsigns, however there seems to be no clear mapping. The best results seem to be achieved by trying to match the `PREFIX POSITION`, fourth and `ICAO` columns to the controllers callsign prefix, or prefix joined with the infix (if it exists) either by underscore or dash.

   Sometimes, even with this method, a callsign doesn't have a clear mapping to exactly one FIR. Take, for example `ENOR_S_CTR`, which could either be `ENOR|Polaris||ENOR` or `ENOR|Bodø RTC - Polaris|ENRC|ENOR`.

3. How can FIRs be matched to FIR boundaries, or the other way around? I discovered an almost perfect mapping from FIR boundaries to FIRs by mapping the FIR boundaries ICAO to the fourth column of FIRs with underscores replaced by dashes when it exists, or the `ICAO` column otherwise. This only leaves unknown FIRs for the FIR boundaries `RKDA-E` `RKDA-C` `UATE` and `UHWW`. Using this mapping the other way around however leaves 17 FIRs without a FIR boundary.

   Also, how are FIRs that have oceanic and non-oceanic boundaries mapped to the correct one, for example `CZQX` or `KZNY`?

There are some more issues I discovered while playing around with the dataset, but I will open a separate issue for those if desired. Please feel free to ask for clarification if needed.

**Comment by Adrian2k** [comment]
`Sometimes, even with this method, a callsign doesn't have a clear mapping to exactly one FIR. Take, for example ENOR_S_CTR, which could either be ENOR|Polaris||ENOR or ENOR|Bodø RTC - `Polaris|ENRC|ENOR.``

The ENRC is not yet in use, but it will be used in the future. It is Bodø Remote Tower Center, which is currently in use IRL in Norway for 2 airports, but soon 10 more will join. This position will then be included on VATSIM if anyone chooses to use it. The reason we have "Polaris" at the end is so it displays "Polaris Control" when someone is online. The reason its mapped to ENOR is as these remoted airports are located all the way from the south to the north.

I have not added a "ENOR-S" entry as it wouldn't be clear where exactly that is for users on VATSpy, since it would be ENBD-S, ENOS, and ENSV. Adding it will just add more unnecessary clutter. We have written clearly in our controller info that we cover from ENVA and south to help with us being displayed in the whole country. If VATSpy one day suddenly supports ENOS_S to be displayed as a separate area I will add it.
