### ISSUE TITLE
South America Control Missing

### ISSUE THREAD

**Issue by Jeeveegee** [vatsimnetwork/vatspy-data-project#198]
New Flight Service Station "South America Control" is missing. Their layout and various sectors can be found on the website: https://fss.vatsa.net/

**Comment by Adrian2k** [comment]
Unfortunately, this can not be included due to the selection of callsigns.
VATSpy only supports callsigns up to the first underscore, so when you have SAM_N_FSS for example VATSpy will only read SAM_FSS.

The solution would be to either change to SAM-N_FSS or SAMN_FSS if the staff team in South America would like this included.
