### ISSUE TITLE
KZNY updated points from 4 days ago seem to have broken it

### ISSUE THREAD

**Issue by o4oren** [vatsimnetwork/vatspy-data-project#208]
See attached image, I tried the points directly on google maps.
<img width="1434" alt="Screen Shot 2020-12-06 at 6 14 43" src="https://user-images.githubusercontent.com/23486326/101271357-98975080-378a-11eb-9a66-fb773fa91d65.png">

**Comment by ajying** [comment]
Hi, I'm on ZNY's staff, I'm not sure I understand what the problem is.

Unless there's some self-intersection or discontinuity issue, the shape shown in your image is correct. For a *very* long time, VatSpy has had an incorrect geometry for ZNY, the new shape now correctly displays the offshore radar airspace that ZNY controls. The long tail that extends down past South Carolina and out past Massachusetts is correct.

**Comment by o4oren** [comment]
I its correct then its correct.
But it runs over KZBW and KZDC now...

**Comment by ajying** [comment]
Yes, that is also the correct behavior. The airspace around New York is very complex and there are different blocks of airspace where different altitudes are allocated to ZNY, ZDC, and ZBW. The latest update is a balance between accuracy and clarity.

**Comment by o4oren** [comment]
One question for you, while we're at it.
How do I determine when new york oceanic is connected? I am asking this is
the context of writing an app that displays vatspy like data on mobile.
If I rely on the ATC call sign prefix both NY_CTR and oceanic will resolve
to the same icao code...
