### ISSUE TITLE
More duplicate airport ICAOs with differing names or positions on pseudo airports

### ISSUE THREAD

**Issue by marvk** [vatsimnetwork/vatspy-data-project#227]
Sorry to come up with this again so quickly after #214 was resolved, but I have found more airports with mismatched names and positions. I had previously assumed that airports with `pseudo=1` are not in use, however, I just realized that is not the case since 

    KJFK|New York|40.63975|-73.778925|NY|KZNY|1

is definitely in use most evenings with the `NY` callsign prefix.

In light of this, the `pseudo` column *is* lacking at least some form of documentation (kind of coming back to #197). After working with the data for some time, I would *assume* `pseudo` airports are used for when one approach or departure controller controlls multiple airports, as is the case with callsign prefixes like `NY`, `ESSEX` or `SOLENT`.

In any case, here are the remaining mismatches, which, at least in some cases *do* seem deliberate as per my reasoning above.

```
Airports with matching ICAO "OJAI" have mismatched names: [Amman-Queen Alia Intl, Amman]
Airports with matching ICAO "KDCA" have mismatched names: [Washington Reagan VA, Washington, Potomac Combined]
Airports with matching ICAO "KFSM" have mismatched names: [Fort Smith Reg. AR, Razorback]
Airports with matching ICAO "KJFK" have mismatched names: [New York-John F. Kennedy Intl NY, New York]
Airports with matching ICAO "KLAX" have mismatched names: [Los Angeles Intl CA, SOCAL Combined]
Airports with matching ICAO "KSFO" have mismatched names: [San Francisco Intl CA, NORCAL Combined]
Airports with matching ICAO "RJAA" have mismatched names: [Tokyo-Narita Intl, Tokyo-Narita]
Airports with matching ICAO "EGHI" have mismatched names: [Southampton, Solent]
Airports with matching ICAO "EGLC" have mismatched names: [London-City, Thames]
Airports with matching ICAO "EGSS" have mismatched names: [London-Stansted, Essex]
```

```
Airports with matching ICAO "YSSY" have mismatched positions: [Point2D [x = 151.176944, y = -33.945833], Point2D [x = 151.177222, y = -33.946111]]
Airports with matching ICAO "EGHI" have mismatched positions: [Point2D [x = -1.356803, y = 50.950261], Point2D [x = -1.8425, y = 50.78]]
```

**Comment by Adrian2k** [comment]
Since those are pseudo positions, they will not display as airports. However the alternative names on the pseudo could still have a purpose, for example at KDCA:

`KDCA|Washington Reagan VA|38.852083|-77.037722|DCA|KZDC|0
KDCA|Washington|38.852083|-77.037722|WAS|KZDC|1
KDCA|Washington|38.852083|-77.037722|DC|KZDC|1
KDCA|Potomac Combined|38.852083|-77.037722|PCT|KZDC|1`

If PCT_APP logs on, it should in say the name put under the psuedo instead of the airport name on the approach circle like so:
![image](https://user-images.githubusercontent.com/35482228/131266074-f57a6fcd-838a-4a50-ae9f-cd873feeece9.png)


I will resolve YSSY and EGHI with mismatching positions, but the remaining data will be kept as now.
