### ISSUE TITLE
[Bug]Airport ICAO code overlap? (FAJA and FAOR)

### ISSUE THREAD

**Issue by amosngSP** [vatsimnetwork/vatspy-data-project#255]
Hello guys, I noticed this weird bug, it seems that there are 2 airports defined with nearly the same coordinates, causing planes with no flightplans to be correlated to the wrong airport (FAJA) when its suppose to be FAOR.
![image](https://user-images.githubusercontent.com/40349656/106301969-5161a380-6293-11eb-8e2b-f75ee0673ae7.png)

**Comment by Adrian2k** [comment]
This FAJA entry seems to be a mistake, FAJA is an FIR, not an airport. So in this case it can be corrected.

However, to answer the general bug here (since it happens in a lot of places), there is not much we can do with the dataset where this issue occurs. When 2 airports/heliports are closer than appx 5km from each other this is a common occurrence, even when the coordinates are set correctly. In such cases, you either have to keep both entries or delete one of them.
