### ISSUE TITLE
SAM_S_FSS Not Showing

### ISSUE THREAD

**Issue by devHazz** [vatsimnetwork/vatspy-data-project#298]
SAM_S_FSS covers SUEO SGFA SARR SACF SAMF SAEF SAVF, Above FL245

**Comment by devHazz** [comment]
Frequency: 134.700

**Comment by Adrian2k** [comment]
Hi.

This is a VATSpy limitation, nothing we can do with the dataset. (The SAM sectors are actually defined in our dataset).
The issue is that VATSpy only reads up to the first underscore, so when SAM_E_FSS is online, VATSpy will only see SAM_FSS.

If SAM were to change to a - instead (SAM-E_FSS) we would be able to display them.
