### ISSUE TITLE
CZQX OCEANIC NO SHOW

### ISSUE THREAD

**Issue by nakoale** [vatsimnetwork/vatspy-data-project#314]
DURING CROSS THE POND CZQZ OCEANIC WAS ONLINE BUT IT DIDNT SHOW ON VATSPY

**Comment by Adrian2k** [comment]
That's because they changed to _CTR callsigns for CTP, most likely due to performance reasons (FSS positions are forced to have a 1500nm range). Since CZQX is both used for domestic and oceanic, this happend.

_CTR logons are displaying domestic, _FSS are displaying oceanic.

It seems like they have reverted back to _FSS logins now.

**Comment by dsolesvik** [comment]
Can further comment on this. We switched to CTR callsigns due to issues with sector ownership when using CZQX_FSS (we weren't able to see aircraft without manually changing a lot of settings every time we logged on), due to an issue with the database system (GNG). Hence, we were instructed to use CTR callsigns on both EGGX and CZQX. CZQX_CTR is Gander Domestic, so we used CZQO_CTR, which didn't display in VATSpy. 
Most controllers are using _FSS at this time and we will be transitioning to _FSS full-time as Andrew resolves the issues with sector ownership, so big kudos to him!
