### ISSUE TITLE
FIRBoundaries, discrepancy between new 'geojson' and old 'dat' format

### ISSUE THREAD

**Issue by AivlaSoft** [vatsimnetwork/vatspy-data-project#517]
Hello,

In the original VAT-Spy text file 'FIRBoundaries.dat' each boundary header provided the two flags "is oceanic" and "is extension", among other data.  Separation character was the pipe-sign, e.g.:

KZHU | 1 | 0 | ... 

The first flag (here 1) is the 'Is Oceanic' flag
The second flag (here 0) is the 'Is Extension' flag           

In one of the last updates provided in the old text file format (around Oct 2021), the following boundaries were flagged as 'is oceanic':
GOOO, KZNY, KZHU, NZCM, RJTG, SUEO, MMZT, ULMM.

In the new geojson format the boundaries GOOO, NZCM, MMZT are no longer flagged as 'is oceanic'.
However, NZCM provides two different polygons, but it is not clear how to determine which one is the 'oceanic' part.

For the following boundaries the old data format has provided two different polygons, where the header of one of them was flagged as 'is extension':
CZQM, CZQX, ESOS, GMMM, KZAK, LECM, LIMM, NFFF, NZZO, SKED, VVHM, WBFC, ZBAA, ZGZU, ZGGG, ZJSY, ZLLL, ZLXY, ZUUU, ZSSS, ZWWW, ZYTX, ZYSH, ZYTL, PAZA, UHMM, UHPP.

In the new geojson data format, the flag 'is extension' is no longer available, or in other words, the new data format has no propery called 'extension'.
There are only a few of the above listed boundaries which provide a second polygon, but it is not clear how to determine which of the polygon is the extension.

Has the oceanic-concept and/or the extension-concept been dropped with this new data format?

Regards,
Urs
(Developer of AivlaSoft EFB)

**Comment by Adrian2k** [comment]
Oceanic: This is not being dropped, but divitions are choosing to use this less. The purpose of this is when both the domestic FIR and the oceanic FIR has the same ICAO code (such as with KZNY for example). This will make any _CTR stations display the non oceanic part and any _FSS stations display the oceanic part. As more and more area's is moving over to _CTR logons instead of _FSS, they have also been changing their FIR codes in these area's. Such as GOOO Oceanic is now GOOC.

Is extention: Has been "misused" (or misunderstood) kinda. The only purpose this had was when a FIR crossed the -180 180 line over the Pacific, but people has also used this when a FIR covers another area if that area is offline. This should no longer be done and FIR's that covers multiple areas should simply have one simple poligon for the whole area. There was a plan to "convert/fix" the areas that had two sectors like this, but his have not been done yet (likely forgotten about).

However why the dataset does not include a isextention, I do not remember the reason for, @NelisV will have to answer that one.

**Comment by NelisV** [comment]
> However why the dataset does not include a isextention

In the GeoJSON spec, it is defined a MultiPolygon should be used when geometry crosses the anti-meridian. 

In cases where 'is extension' was used in the past, we checked if these polygons had shared borders with the 'main' polygon, if this was the case these were kept as 2 separate polygons. If they did not have shared borders, they have been merged into one MultiPolygon, as it's considered good practice for MultiPolygons not to have shared borders.

**Comment by AivlaSoft** [comment]
Thanks very much @Adrian2k and @NelisV for this explanation. It helps me a lot and finally it makes the code easier.

**Comment by AivlaSoft** [comment]
Just another question that came up while implementing the new geojson format:

Certain boundaries have _identical_ header information, while the arrays of positions (Lat/Long) are _different_, such as CZQM, CZQX, ESOS and maybe some more. What is the criterion to determine which of boundary of each of these pairs is the active one? How to distinguish between them?

**Comment by NelisV** [comment]
For these polygons it means they should all be active if their ID matches the station online.
