### ISSUE TITLE
EURW-N missing sector

### ISSUE THREAD

**Issue by seelenkrieger** [vatsimnetwork/vatspy-data-project#630]
@ EURW-N is a missing sector in middle of France (south of LFPG)
see attachment

![image](https://user-images.githubusercontent.com/55149789/208680209-e576d479-c5f8-4f2a-9bff-716d758c3b23.png)

Edit: seems LFFF is missing in the UIR section of EURW-N

**Comment by Soofushka** [comment]
Let me do it)

**Comment by ClipperWings** [comment]
@seelenkrieger @ziplock1 
This is intentional, as Paris (FF) is a lower FIR controlling below FL 295. 
UIR FL295 and above are covered by both Reims (EE) or Brest East (RR-E) since FF covers FL 295 and below. It has been agreed with the French vACC not to cover below this level, thus respecting UIR in both Brest and Reims FIRs per IRL ops and the French vACC request. 

So to resume:
EUC-WN_CTR covers :

FL295 in RR-E, EE, BB
FL255 in the rest of RR
FL245 in MM
FF is nil.

I hope to have answered your question.

**Comment by Adrian2k** [comment]
Several changes was done here - https://github.com/vatsimnetwork/vatspy-data-project/pull/698
Reopen a new issue if the problem still concists
